console.log(Infinity);
console.log(-Infinity);
console.log("isFinite() = " + isFinite());
console.log('isFinite("1") = ' + isFinite("1"));
console.log("isFinite(true) = " + isFinite(true));
console.log("isFinite([]) = " + isFinite([]));
console.log("isFinite([1]) = " + isFinite([1]));
console.log("isFinite([[1]]) = " + isFinite([[1]]));
console.log("isFinite([1,2]) = " + isFinite([1, 2]));
console.log("isFinite([Infinity]) = " + isFinite([Infinity]));
console.log("isFinite({}) = " + isFinite({}));
console.log("isFinite(5) = " + isFinite(5));
console.log("isFinite(NaN) = " + isFinite(NaN));
console.log("isFinite(Infinity) = " + isFinite(Infinity));
console.log("isFinite(1, Infinity) = " + isFinite(1, Infinity));
console.log("isFinite(Infinity, 1) = " + isFinite(Infinity, 1));
