COFFEE_FILES=\
	nodevisitor.coffee		\
	compiler.coffee			\
	typeinfer.coffee		\
	debug.coffee			\
	echo-util.coffee		\
	echo-desugar.coffee		\
	closure-conversion.coffee	\
	set.coffee

all:
	coffee -o coffee -c $(COFFEE_FILES)