# The node native addon that gives the node-hosted (stage0) compiler access
# to LLVM.  Built out-of-band with node-gyp (`./build-addon.sh`); buck just
# picks up the built addon.
#
# TODO(buck2): drive node-gyp from a genrule so this is built hermetically.
export_file(
    name = "llvm.node",
    src = "build/Release/llvm.node",
    visibility = ["PUBLIC"],
)
