import os

def set_options(opt):
  opt.tool_options("compiler_cxx")

def configure(conf):
  conf.check_tool("compiler_cxx")
  conf.check_tool("node_addon")

def build(bld):
  print(os.environ.get("FOO"));

  obj = bld.new_task_gen("cxx", "shlib", "node_addon")

  for flag in os.environ.get("LLVM_LINKFLAGS").split(" "):
    bld.env.append_value('LINKFLAGS', flag)

  # taken from llvm-config --cxxflags

  obj.cxxflags = os.environ.get("LLVM_CXXFLAGS").split(" ")
  obj.target = "llvm"
  obj.source = ["allocainst.cpp",
  	        "arraytype.cpp",
                "basicblock.cpp",
  	        "callinvoke.cpp",
                "constant.cpp",
                "constantagg.cpp",
                "constantarray.cpp",
                "constantfp.cpp",
		"dibuilder.cpp",
                "function.cpp",
                "functiontype.cpp",
                "globalvariable.cpp",
                "irbuilder.cpp",
                "instruction.cpp",
                "landingpad.cpp",
		"loadinst.cpp",
		"metadata.cpp",
                "module.cpp",
                "node-llvm.cpp",
                "phinode.cpp",
                "structtype.cpp",
                "switch.cpp",
                "type.cpp",
                "value.cpp"]
